CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL UNIQUE,
  password TEXT
);
CREATE TABLE IF NOT EXISTS auth (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  provider TEXT NOT NULL,
  user INTEGER NOT NULL,
  oauth2_user TEXT NOT NULL UNIQUE,
  FOREIGN KEY(user) REFERENCES user(id)
);
CREATE TABLE IF NOT EXISTS session (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cookie TEXT NOT NULL UNIQUE,
  userid INTEGER NOT NULL,
  createAt TEXT NOT NULL,
  userAgent TEXT NOT NULL,
  reason INTEGER,
  FOREIGN KEY(userid) REFERENCES user(id)
);

