{
 "title": "Global",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(container_last_seen)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU / container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total[5m]) * 100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory / container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "container_memory_usage_bytes", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Receive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total[5m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Transmit Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total[5m])",
     "legendFormat": "{{interface}}"
    }
   ]
  }
 ]
}